import React from 'react';

/**
 * Material Symbols Rounded Icon Component
 *
 * Maps codicon names to Material Symbols Rounded equivalents.
 * Falls back gracefully for unmapped icons.
 *
 * Usage:
 *   <Icon name="search" />
 *   <Icon name="settings" size={24} />
 *   <Icon name="close" fill />
 *   <Icon name="loading" spin />
 */

// Codicon → Material Symbols mapping (focused on icons used in USXD)
const ICON_MAP: Record<string, string> = {
  // Navigation
  'chevron-right': 'chevron_right',
  'chevron-down': 'expand_more',
  'chevron-up': 'expand_less',
  'chevron-left': 'chevron_left',
  'arrow-right': 'arrow_forward',
  'arrow-left': 'arrow_back',
  'arrow-up': 'arrow_upward',
  'arrow-down': 'arrow_downward',
  'expand-all': 'unfold_more',
  'collapse-all': 'unfold_less',

  // Actions
  'add': 'add',
  'remove': 'remove',
  'close': 'close',
  'check': 'check',
  'refresh': 'refresh',
  'search': 'search',
  'search-stop': 'stop',
  'settings-gear': 'settings',
  'settings': 'settings',
  'edit': 'edit',
  'delete': 'delete',
  'trash': 'delete',
  'copy': 'content_copy',
  'paste': 'content_paste',
  'cut': 'content_cut',
  'save': 'save',
  'undo': 'undo',
  'redo': 'redo',
  'more': 'more_vert',
  'filter': 'filter_list',
  'sort': 'sort',
  'menu': 'menu',
  'home': 'home',
  'info': 'info',
  'help': 'help',
  'warning': 'warning',
  'error': 'error',
  'danger': 'error',
  'success': 'check_circle',
  'notification': 'notifications',
  'bell': 'notifications',
  'star': 'star',
  'star-full': 'star',
  'favorite': 'favorite',
  'share': 'share',
  'upload': 'upload',
  'download': 'download',
  'cloud-download': 'cloud_download',
  'cloud-upload': 'cloud_upload',
  'play': 'play_arrow',
  'pause': 'pause',
  'stop': 'stop',
  'record': 'radio_button_checked',
  'loading': 'sync',
  'spin': 'sync',
  'modifier-spin': 'sync',

  // Files & Documents
  'file': 'description',
  'file-text': 'description',
  'folder': 'folder',
  'folder-open': 'folder_open',
  'files': 'folder',
  'new-file': 'note_add',
  'new-folder': 'create_new_folder',
  'document': 'description',
  'notebook': 'book',
  'book': 'book',
  'archive': 'archive',
  'inbox': 'inbox',
  'outbox': 'outbox',
  'trashcan': 'delete',
  'project': 'folder_special',
  'checklist': 'checklist',
  'list-tree': 'list_alt',
  'list': 'list',
  'grid': 'grid_view',
  'table': 'table',
  'kanban': 'view_column',
  'library': 'library_books',

  // Code & Dev
  'terminal': 'terminal',
  'code': 'code',
  'debug': 'bug_report',
  'bug': 'bug_report',
  'console': 'terminal',
  'git-branch': 'call_split',
  'git-commit': 'commit',
  'git-pull': 'download',
  'git-push': 'upload',
  'source-control': 'account_tree',
  'repo': 'inventory_2',
  'remote': 'cloud',
  'symbol-file': 'insert_drive_file',
  'symbol-key': 'vpn_key',
  'symbol-misc': 'widgets',
  'symbol-property': 'data_object',
  'symbol-enum': 'data_array',
  'symbol-class': 'data_object',
  'symbol-interface': 'data_array',
  'symbol-function': 'function',
  'symbol-variable': 'variable',
  'symbol-constant': 'lock',
  'symbol-method': 'functions',
  'symbol-module': 'module',
  'symbol-namespace': 'dns',
  'symbol-package': 'package',
  'symbol-string': 'text_fields',
  'symbol-number': 'numbers',
  'symbol-boolean': 'toggle_on',
  'symbol-array': 'data_array',
  'symbol-object': 'data_object',
  'symbol-field': 'data_object',
  'symbol-enum-member': 'data_array',
  'symbol-struct': 'data_object',
  'symbol-event': 'event',
  'symbol-operator': 'calculate',
  'symbol-type-parameter': 'data_object',
  'pass': 'verified',
  'check-all': 'done_all',

  // UI Elements
  'search-clear': 'close',
  'clear': 'close',
  'search-input-clear': 'close',
  'clear-all': 'clear_all',
  'color-mode': 'dark_mode',
  'light-bulb': 'light_mode',
  'lightbulb': 'light_mode',
  'dark-mode': 'dark_mode',
  'light-mode': 'light_mode',
  'font': 'font_download',
  'type': 'text_fields',
  'image': 'image',
  'photo': 'photo',
  'camera': 'camera_alt',
  'video': 'videocam',
  'audio': 'mic',
  'music': 'music_note',
  'link': 'link',
  'unlink': 'link_off',
  'external-link': 'open_in_new',
  'fullscreen': 'fullscreen',
  'fullscreen-exit': 'fullscreen_exit',
  'minimize': 'minimize',
  'maximize': 'maximize',
  'restore': 'restore',
  'resize': 'aspect_ratio',
  'dock': 'dock_to_bottom',
  'undock': 'dock_to_bottom',
  'split-horizontal': 'horizontal_split',
  'split-vertical': 'vertical_split',
  'layout': 'view_quilt',
  'panel': 'view_sidebar',
  'sidebar': 'view_sidebar',
  'activity-bar': 'view_sidebar',
  'status-bar': 'bottom_panel_open',

  // Communication
  'comment': 'comment',
  'comment-discussion': 'forum',
  'chat': 'chat',
  'message': 'message',
  'mail': 'mail',
  'email': 'mail',
  'send': 'send',
  'reply': 'reply',
  'robot': 'smart_toy',
  'ai': 'auto_awesome',
  'sparkle': 'auto_awesome',
  'magic': 'auto_awesome',
  'mortar-board': 'school',
  'school': 'school',
  'user': 'person',
  'person': 'person',
  'people': 'people',
  'group': 'group',
  'account': 'account_circle',
  'profile': 'account_circle',
  'login': 'login',
  'logout': 'logout',

  // Status & Indicators
  'circle-filled': 'circle',
  'circle-outline': 'circle_outlined',
  'circle-large': 'circle',
  'circle-large-outline': 'circle_outlined',
  'primitive-dot': 'circle',
  'primitive-square': 'square',
  'radio-on': 'radio_button_checked',
  'radio-off': 'radio_button_unchecked',
  'check-on': 'check_box',
  'check-off': 'check_box_outline_blank',
  'loading-spin': 'sync',
  'sync': 'sync',
  'sync-ignored': 'sync_disabled',
  'sync-pending': 'sync_problem',

  // Extensions & Marketplace
  'extensions': 'extension',
  'extension': 'extension',
  'puzzle': 'extension',
  'marketplace': 'store',
  'store': 'store',
  'package': 'package',
  'gift': 'card_giftcard',
  'tag': 'sell',
  'tags': 'sell',
  'label': 'label',
  'bookmark': 'bookmark',
  'pin': 'push_pin',
  'flag': 'flag',
  'clock': 'schedule',
  'history': 'history',
  'time': 'schedule',
  'calendar': 'calendar_today',
  'date': 'calendar_today',
  'alarm': 'alarm',
  'timer': 'timer',

  // Media Controls
  'play-circle': 'play_circle',
  'pause-circle': 'pause_circle',
  'stop-circle': 'stop_circle',
  'skip-back': 'skip_previous',
  'skip-forward': 'skip_next',
  'previous': 'skip_previous',
  'next': 'skip_next',
  'shuffle': 'shuffle',
  'repeat': 'repeat',
  'volume-up': 'volume_up',
  'volume-down': 'volume_down',
  'volume-off': 'volume_off',
  'mute': 'volume_off',
  'mic': 'mic',
  'mic-mute': 'mic_off',
  'headphones': 'headphones',
  'speaker': 'speaker',

  // Network & Devices
  'wifi': 'wifi',
  'bluetooth': 'bluetooth',
  'network': 'lan',
  'server': 'dns',
  'database': 'storage',
  'cloud': 'cloud',
  'device-desktop': 'desktop_windows',
  'device-mobile': 'smartphone',
  'device-tablet': 'tablet',
  'laptop': 'laptop',
  'monitor': 'monitor',
  'tv': 'tv',
  'print': 'print',
  'scan': 'scan',
  'fax': 'fax',

  // Shapes & Objects
  'triangle-down': 'arrow_drop_down',
  'triangle-up': 'arrow_drop_up',
  'triangle-left': 'arrow_drop_left',
  'triangle-right': 'arrow_drop_right',
  'dash': 'horizontal_rule',
  'ellipsis': 'more_horiz',
  'kebab': 'more_vert',
  'grip': 'drag_indicator',
  'grabber': 'drag_indicator',
  'handle': 'drag_indicator',
  'reorder': 'reorder',
  'drag': 'drag_indicator',
  'move': 'open_with',
  'select': 'select_all',
  'cursor': 'mouse',
  'pointer': 'touch_app',
  'hand': 'pan_tool',
  'zoom-in': 'zoom_in',
  'zoom-out': 'zoom_out',
  'zoom': 'search',
  'lock': 'lock',
  'unlock': 'lock_open',
  'key': 'vpn_key',
  'security': 'security',
  'shield': 'shield',
  'verified': 'verified',
  'new': 'fiber_new',
  'hot': 'local_fire_department',
  'trending': 'trending_up',
  'popular': 'trending_up',
  'new-releases': 'new_releases',
  'update': 'system_update',
  'upgrade': 'system_update_alt',
  'install': 'download',
  'uninstall': 'delete',
  'configure': 'tune',
  'tools': 'build',
  'wrench': 'build',
  'hammer': 'construction',
  'screwdriver': 'build',
  'compass': 'explore',
  'globe': 'language',
  'map': 'map',
  'location': 'location_on',
  'pin-drop': 'push_pin',
  'navigation': 'navigation',
  'directions': 'directions',
  'walk': 'directions_walk',
  'run': 'directions_run',
  'bike': 'directions_bike',
  'car': 'directions_car',
  'bus': 'directions_bus',
  'train': 'directions_train',
  'flight': 'flight',
  'boat': 'directions_boat',
  'anchor': 'anchor',
  'sailing': 'sailing',
  'campaign': 'campaign',
  'announcement': 'campaign',
  'megaphone': 'campaign',
  'feedback': 'feedback',
  'rate-review': 'rate_review',
  'thumbs-up': 'thumb_up',
  'thumbs-down': 'thumb_down',
  'like': 'thumb_up',
  'dislike': 'thumb_down',
  'visibility': 'visibility',
  'visibility-off': 'visibility_off',
  'eye': 'visibility',
  'eye-off': 'visibility_off',
  'preview': 'visibility',
  'inspect': 'visibility',
  'qr': 'qr_code',
  'barcode': 'qr_code_scanner',
  'wallet': 'wallet',
  'credit-card': 'credit_card',
  'payment': 'credit_card',
  'cart': 'shopping_cart',
  'shopping': 'shopping_bag',
  'storefront': 'storefront',
  'receipt': 'receipt',
  'invoice': 'receipt_long',
  'analytics': 'analytics',
  'chart': 'bar_chart',
  'graph': 'show_chart',
  'pie-chart': 'pie_chart',
  'donut': 'donut_large',
  'dashboard': 'dashboard',
  'widget': 'widgets',
  'gadget': 'widgets',
  'app': 'apps',
  'apps': 'apps',
  'launch': 'launch',
  'rocket': 'rocket',
  'science': 'science',
  'experiment': 'science',
  'biotech': 'biotech',
  'psychology': 'psychology',
  'auto-awesome': 'auto_awesome',
  'magic-button': 'auto_awesome',
  'auto-fix': 'auto_fix_high',
  'magic-wand': 'auto_fix_high',
  'palette': 'palette',
  'color': 'palette',
  'brush': 'brush',
  'paint': 'format_paint',
  'fill': 'format_color_fill',
  'stroke': 'border_color',
  'border': 'border_all',
  'radius': 'radius',
  'shape': 'category',
  'rounded-corner': 'rounded_corner',
  'straight': 'straighten',
  'crop': 'crop',
  'rotate': 'rotate_right',
  'flip': 'flip',
  'transform': 'transform',
  'layers': 'layers',
  'align-left': 'format_align_left',
  'align-center': 'format_align_center',
  'align-right': 'format_align_right',
  'align-justify': 'format_align_justify',
  'bold': 'format_bold',
  'italic': 'format_italic',
  'underline': 'format_underline',
  'strikethrough': 'format_strikethrough',
  'text-color': 'format_color_text',
  'text-size': 'format_size',
  'heading': 'title',
  'subtitle': 'subtitles',
  'paragraph': 'format_paragraph',
  'list-ordered': 'format_list_numbered',
  'list-unordered': 'format_list_bulleted',
  'indent': 'format_indent_increase',
  'outdent': 'format_indent_decrease',
  'quote': 'format_quote',
  'code-block': 'code',
  'table-insert': 'table',
  'column': 'view_column',
  'row': 'view_row',
  'cell': 'grid_on',
  'merge': 'merge',
  'split': 'split',
  'formula': 'functions',
  'math': 'calculate',
  'sum': 'summarize',
  'count': 'exposure_zero',
  'average': 'exposure',
  'min': 'arrow_downward',
  'max': 'arrow_upward',
  'filter-alt': 'filter_alt',
  'filter-off': 'filter_alt_off',
  'search-off': 'search_off',
  'find': 'find_in_page',
  'find-replace': 'find_replace',
  'replace': 'find_replace',
  'replace-all': 'find_replace',
  'jump': 'open_in_new',
  'go-to': 'open_in_new',
  'open': 'open_in_new',
  'new-window': 'open_in_new',
  'pop-out': 'open_in_new',
  'pop-in': 'close_fullscreen',
  'attach': 'attach_file',
  'attachment': 'attachment',
  'clipboard': 'content_paste',
  'copy-to': 'content_copy',
  'cut-from': 'content_cut',
  'paste-from': 'content_paste',
  'select-all': 'select_all',
  'select-none': 'deselect',
  'invert': 'invert_colors',
  'swap': 'swap_horiz',
  'exchange': 'swap_horiz',
  'transfer': 'swap_horiz',
  'import': 'file_download',
  'export': 'file_upload',
  'backup': 'backup',
  'restore-page': 'restore_page',
  'history-toggle': 'history_toggle_off',
  'timeline': 'timeline',
  'tree': 'account_tree',
  'org-chart': 'account_tree',
  'flow': 'account_tree',
  'diagram': 'account_tree',
  'mind-map': 'account_tree',
  'network-diagram': 'hub',
  'hub': 'hub',
  'node': 'circle',
  'edge': 'linear_scale',
  'connection': 'linear_scale',
  'line': 'horizontal_rule',
  'arrow': 'arrow_forward',
  'bracket': 'code',
  'brace': 'curly_braces',
  'parenthesis': 'data_object',
  'angle': 'chevron_right',
  'pipe': 'more_vert',
  'slash': 'horizontal_rule',
  'backslash': 'horizontal_rule',
  'colon': 'more_vert',
  'semicolon': 'more_vert',
  'comma': 'more_horiz',
  'period': 'more_horiz',
  'space': 'space_bar',
  'tab': 'keyboard_tab',
  'enter': 'keyboard_return',
  'escape': 'keyboard_escape',
  'delete-left': 'backspace',
  'delete-right': 'delete',
  'insert': 'add',
  'home-key': 'home',
  'end-key': 'end',
  'page-up': 'keyboard_page_up',
  'page-down': 'keyboard_page_down',
  'shift': 'keyboard_shift',
  'ctrl': 'keyboard_control',
  'alt': 'keyboard_option',
  'meta': 'keyboard_command',
  'command': 'keyboard_command',
  'option': 'keyboard_option',
  'control': 'keyboard_control',
  'caps-lock': 'keyboard_capslock',
  'num-lock': 'keyboard_numlock',
  'scroll-lock': 'keyboard',
  'print-screen': 'print',
  'pause-break': 'pause',
  'insert-key': 'add',
  'windows': 'window',
  'apple': 'apple',
  'linux': 'linux',
  'android': 'android',
  'chrome': 'language',
  'firefox': 'language',
  'safari': 'language',
  'ie': 'language',
  'opera': 'language',
  'brave': 'language',
  'electron': 'electron',
  'nodejs': 'node',
  'npm': 'npm',
  'yarn': 'yarn',
  'pnpm': 'pnpm',
  'docker': 'docker',
  'kubernetes': 'deployed_code',
  'k8s': 'deployed_code',
  'aws': 'cloud',
  'gcp': 'cloud',
  'azure': 'cloud',
  'firebase': 'cloud',
  'supabase': 'cloud',
  'vercel': 'cloud',
  'netlify': 'cloud',
  'heroku': 'cloud',
  'digitalocean': 'cloud',
  'linode': 'cloud',
  'vultr': 'cloud',
  'ovh': 'cloud',
  'scaleway': 'cloud',
  'civo': 'cloud',
  'exoscale': 'cloud',
  'upcloud': 'cloud',
  'baremetal': 'dns',
  'vps': 'dns',
  'dedicated': 'dns',
  'shared': 'cloud',
  'vpc': 'cloud',
  'subnet': 'cloud',
  'firewall': 'shield',
  'load-balancer': 'account_tree',
  'cdn': 'cloud',
  'dns': 'dns',
  'domain': 'language',
  'ssl': 'lock',
  'tls': 'lock',
  'certificate': 'verified',
  'key-pair': 'vpn_key',
  'ssh': 'vpn_key',
  'api': 'api',
  'rest': 'api',
  'graphql': 'api',
  'grpc': 'api',
  'websocket': 'api',
  'webhook': 'webhook',
  'hook': 'webhook',
  'endpoint': 'api',
  'route': 'alt_route',
  'middleware': 'alt_route',
  'controller': 'alt_route',
  'service': 'dns',
  'microservice': 'dns',
  'monolith': 'dns',
  'serverless': 'cloud',
  'lambda': 'functions',
  'function': 'functions',
  'trigger': 'bolt',
  'event': 'event',
  'queue': 'queue',
  'topic': 'topic',
  'pubsub': 'hub',
  'stream': 'stream',
  'pipeline': 'account_tree',
  'workflow': 'account_tree',
  'job': 'work_history',
  'task': 'task_alt',
  'cron': 'schedule',
  'schedule': 'schedule',
  'timer-off': 'timer_off',
  'timer-pause': 'timer_pause',
  'timer-play': 'timer_play',
  'timer-sand': 'hourglass_empty',
  'hourglass': 'hourglass_empty',
  'sand-clock': 'hourglass_empty',
  'stopwatch': 'timer',
  'countdown': 'timer',
  'countup': 'timer',
  'elapsed': 'timer',
  'remaining': 'timer',
  'due': 'event',
  'overdue': 'event_busy',
  'completed': 'task_alt',
  'in-progress': 'pending',
  'pending': 'pending',
  'cancelled': 'cancel',
  'blocked': 'block',
  'on-hold': 'pause_circle',
  'backlog': 'inbox',
  'sprint': 'sprint',
  'epic': 'epic',
  'story': 'auto_stories',
  'issue': 'bug_report',
  'bug-report': 'bug_report',
  'feature': 'new_releases',
  'enhancement': 'trending_up',
  'improvement': 'trending_up',
  'refactor': 'construction',
  'chore': 'cleaning_services',
  'docs': 'description',
  'documentation': 'description',
  'test': 'science',
  'testing': 'science',
  'qa': 'science',
  'quality': 'verified',
  'code-review': 'rate_review',
  'review': 'rate_review',
  'approve': 'verified',
  'reject': 'cancel',
};

export interface IconProps {
  name: string;
  size?: number | string;
  className?: string;
  fill?: boolean;
  weight?: number;
  grade?: number;
  opticalSize?: number;
  spin?: boolean;
  style?: React.CSSProperties;
  onClick?: () => void;
  title?: string;
}

/**
 * Resolve a codicon-style icon name to a Material Symbols name.
 * Falls back to the original name if not found in the map.
 */
export function resolveIconName(name: string): string {
  return ICON_MAP[name] || name;
}

/**
 * Material Symbols Rounded Icon component.
 *
 * Renders a <span> with the Material Symbols icon font.
 * Supports fill, weight, grade, optical size, and spin.
 */
/** Map string size names to pixel values */
const SIZE_MAP: Record<string, number> = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
};

/** Resolve size to a number */
function resolveSize(size?: number | string): number {
  if (size === undefined || size === null) return 16;
  if (typeof size === 'number') return size;
  return SIZE_MAP[size] || 16;
}

export const Icon: React.FC<IconProps> = ({
  name,
  size = 16,
  className = '',
  fill = false,
  weight = 400,
  grade = 0,
  opticalSize = 48,
  spin = false,
  style,
  onClick,
  title,
}) => {
  const iconName = resolveIconName(name);
  const resolvedSize = resolveSize(size);

  const iconStyle: React.CSSProperties = {
    fontVariationSettings: `'FILL' ${fill ? 1 : 0}, 'wght' ${weight}, 'GRAD' ${grade}, 'opsz' ${opticalSize}`,
    fontSize: resolvedSize,
    width: resolvedSize,
    height: resolvedSize,
    lineHeight: 1,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    ...style,
  };

  const classNames = [
    'material-symbols-rounded',
    spin ? 'm3-icon-spin' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <span
      className={classNames}
      style={iconStyle}
      onClick={onClick}
      role={onClick ? 'button' : undefined}
      tabIndex={onClick ? 0 : undefined}
      aria-hidden={!onClick}
      title={title}
    >
      {iconName}
    </span>
  );
};

export default Icon;
